version: '3'
services:
  postgres:
    container_name: postgres-9.6
    restart: always
    image: postgres:9.6
    env_file:
      - ./.env.postgresql
    ports:
      - '5432:5432'
    volumes:
      - postgresqldata:/var/lib/postgresql/data
volumes:
  postgresqldata:
