version: '3'
services:
  postgres:
    container_name: postgres-9.6
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql
