version: '3'
services:
  mysql:
    container_name: mysql-5.7
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
