version: '3'
services:
  mysql:
    container_name: mysql-5.7
    restart: always
    image: mysql:5.7
    env_file:
      - ./.env.mysql
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
